#!/bin/sh
# None of these tests make sense if the C compiler is broken
cat > conftest.c << EOF
#include <stdlib.h>
int main() {
    return 0;
}
EOF
echo1 "Checking whether the C compiler ($CC) works... "
if conftest; then
    echo2 yes
else
    echo2 no
    cat << EOF
  configure: Aborting. Your C compiler ($CC) does not seem to work.
EOF
    exit 1;
fi

