#!/bin/sh

# These checks are warnings only
echo1 "Checking for /usr/bin/perl..."

lf="$(/usr/bin/perl -V:uselargefiles 2>/dev/null)"

if [ 0 -ne $? ]; then
    echo2 "not found"
    cat << EOF

You do not appear to have /usr/bin/perl on your system. Even though perl is
not required for using magicrescue, you should be aware that many of the
included recipes and tools require it.

EOF
else
    if echo "$lf"|grep define >/dev/null; then
        echo2 "ok"
    else
	echo2 "present"
	cat << EOF

You have perl, but support for large files is not enabled. You should either
recompile perl with -Duselargefiles or chop your files into 2GB pieces to use
any of the recipes that require perl.

EOF
    fi
fi
